import { useFeedback } from '../../ds';
import { useEffect, useState } from 'react';
import { Feedback, Field, memberAPI, useAction, type Family } from './shared';
type Person = { id: string; name: string; note: string };
type Edge = { source: string; target: string; relation: string };
type Group = { id: string; name: string; mine: boolean; people: Person[]; edges: Edge[]; members: { id: string; handle: string; accepted: boolean; role: string }[] };
export function FamilySpace() {
 const action = useAction(), fb = useFeedback(), [families, setFamilies] = useState<Family[]>([]), [selected, setSelected] = useState(''), [group, setGroup] = useState<Group | null>(null);
 const [name, setName] = useState(''), [personName, setPersonName] = useState(''), [note, setNote] = useState(''), [consent, setConsent] = useState(false), [handle, setHandle] = useState(''), [role, setRole] = useState('viewer');
 const [source, setSource] = useState(''), [target, setTarget] = useState(''), [relation, setRelation] = useState('parent');
 const load = async () => { setFamilies(await memberAPI('/api/families')); if (selected) setGroup((await memberAPI<Group[]>(`/api/families/${selected}`))[0]); };
 useEffect(() => { void action.run(load); }, [selected]);
 const act = (fn: () => Promise<unknown>) => void action.run(async () => { await fn(); await load(); });
 const label = (id: string) => group?.people.find(p => p.id === id)?.name || 'Relative';
 return <><div className="card"><p className="kicker">Roots & relationships</p><h2>Your family space</h2><p>Family groups are private. Invite relatives to participate; a tree entry does not create a social or matrimony account.</p>
 <form onSubmit={e => { e.preventDefault(); act(async () => { await memberAPI('/api/families', 'POST', { name }); setName(''); }); }}><Field label="New family group name"><input required maxLength={100} value={name} onChange={e => setName(e.target.value)} /></Field><button disabled={action.busy}>Create private group</button></form>
 <Feedback {...action} /></div><div className="chips">{families.map(f => <div className="card" key={f.id}><strong>{f.name}</strong><p>Created by @{f.owner_handle}</p>{f.mine || f.accepted ? <button onClick={() => { setGroup(null); setSelected(f.id); }}>{selected === f.id ? 'Selected' : 'Open group'}</button> : <><button onClick={() => act(() => memberAPI(`/api/families/${f.id}/members`, 'POST', { action: 'accept' }))}>Accept invitation</button><button onClick={() => act(() => memberAPI(`/api/families/${f.id}/members`, 'POST', { action: 'leave' }))}>Decline</button></>}</div>)}</div>
 {group && <><section className="card"><h2>{group.name}</h2><div className="family-tree"><svg role="img" aria-label="Family relationship map" viewBox={`0 0 720 ${Math.max(150, Math.ceil(group.people.length / 3) * 130)}`}>
 {group.edges.map((edge, i) => { const a = group.people.findIndex(p => p.id === edge.source), b = group.people.findIndex(p => p.id === edge.target); if (a < 0 || b < 0) return null; return <line key={i} x1={120 + a % 3 * 240} y1={60 + Math.floor(a / 3) * 130} x2={120 + b % 3 * 240} y2={60 + Math.floor(b / 3) * 130} stroke="#d6b467" strokeWidth="2" />; })}
 {group.people.map((p, i) => <g key={p.id} transform={`translate(${i % 3 * 240 + 20},${Math.floor(i / 3) * 130 + 30})`}><rect width="200" height="65" rx="16" fill="#172238" stroke="#52647e" /><text x="100" y="38" textAnchor="middle" fill="#eee">{p.name.length > 20 ? p.name.slice(0, 19) + '…' : p.name}</text></g>)}
 </svg></div>{!group.people.length && <p>Add people to start your tree.</p>}
 <ul>{group.edges.map((edge, i) => <li key={i}>{label(edge.source)} → {edge.relation.replaceAll('_', ' ')} of → {label(edge.target)} <button onClick={() => act(() => memberAPI(`/api/families/${selected}/edges`, 'DELETE', edge))}>Remove link</button></li>)}</ul>
 <div className="grid-3">{group.people.map(p => <div className="card" key={p.id}><strong>{p.name}</strong><p>{p.note}</p><button onClick={async () => { if (await fb.confirm({ title: `Remove ${p.name} and their links from this group?` })) act(() => memberAPI(`/api/families/${selected}/people/${p.id}`, 'DELETE')); }}>Remove person</button></div>)}</div>
 </section><div className="grid-2"><form className="card" onSubmit={e => { e.preventDefault(); act(async () => { await memberAPI(`/api/families/${selected}/people`, 'POST', { name: personName, note, consent }); setPersonName(''); setNote(''); setConsent(false); }); }}><h3>Add a relative</h3><Field label="Name or private placeholder"><input required maxLength={100} value={personName} onChange={e => setPersonName(e.target.value)} /></Field><Field label="Short family note"><textarea maxLength={300} value={note} onChange={e => setNote(e.target.value)} /></Field><label><input type="checkbox" required checked={consent} onChange={e => setConsent(e.target.checked)} /> I have permission to share this person's details with this family group, or this is an unnamed placeholder.</label><button disabled={action.busy}>Add person</button></form>
 <form className="card" onSubmit={e => { e.preventDefault(); act(() => memberAPI(`/api/families/${selected}/edges`, 'POST', { source, target, relation })); }}><h3>Connect relatives</h3><Field label="Person"><select required value={source} onChange={e => setSource(e.target.value)}><option value="">Choose</option>{group.people.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Relationship to the other person"><select value={relation} onChange={e => setRelation(e.target.value)}>{['parent', 'adoptive_parent', 'step_parent', 'guardian', 'partner', 'sibling'].map(v => <option key={v}>{v}</option>)}</select></Field><Field label="Other person"><select required value={target} onChange={e => setTarget(e.target.value)}><option value="">Choose</option>{group.people.filter(p => p.id !== source).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><button disabled={action.busy}>Add relationship</button></form></div>
 <section className="card"><h3>Group access</h3>{group.members.map(m => <p key={m.id}>@{m.handle} · {m.role} · {m.accepted ? 'Joined' : 'Invited'} {group.mine && <button onClick={() => act(() => memberAPI(`/api/families/${selected}/members`, 'POST', { action: 'remove', handle: m.handle }))}>Revoke access</button>}</p>)}
 {group.mine ? <><form onSubmit={e => { e.preventDefault(); act(async () => { await memberAPI(`/api/families/${selected}/members`, 'POST', { action: 'invite', handle, role }); setHandle(''); }); }}><Field label="Invite existing account by handle"><input required value={handle} onChange={e => setHandle(e.target.value)} /></Field><Field label="Permission"><select value={role} onChange={e => setRole(e.target.value)}><option value="viewer">View only</option><option value="editor">Edit tree</option></select></Field><button disabled={action.busy}>Invite</button></form><button onClick={async () => { if (await fb.confirm({ title: 'Delete this family group?', body: 'Its tree and family-only posts are deleted for everyone.', confirm: 'Delete group', danger: true })) void action.run(async () => { await memberAPI(`/api/families/${selected}`, 'DELETE'); setSelected(''); setGroup(null); setFamilies(await memberAPI('/api/families')); }); }}>Delete group</button></> : <button onClick={() => void action.run(async () => { await memberAPI(`/api/families/${selected}/members`, 'POST', { action: 'leave' }); setSelected(''); setGroup(null); setFamilies(await memberAPI('/api/families')); })}>Leave group</button>}
 </section></>}
 </>;
}
