import { useFeedback } from '../../ds';
import {useEffect,useState} from 'react';
import {memberAPI,Field,Feedback,useAction,type Family} from './shared';
type Grant={owner:string;delegate:string;mine:boolean;handle:string;accepted:boolean;expires_at:string;available:boolean};
type Pick={owner:string;delegate:string;candidate:string;note:string;candidate_handle:string;delegate_handle:string;mine:boolean};
type Candidate={id:string;handle:string;age:number;details:{introduction:string;city:string;display_name?:string};shared_interests:string[];reasons?:string[]};
export function FamilyAssistance(){
 const action=useAction(), fb = useFeedback();const [grants,setGrants]=useState<Grant[]>([]),[picks,setPicks]=useState<Pick[]>([]),[families,setFamilies]=useState<Family[]>([]);
 const [handle,setHandle]=useState(''),[family,setFamily]=useState(''),[owner,setOwner]=useState(''),[candidates,setCandidates]=useState<Candidate[]>([]);
 async function refresh(){const [g,p,f]=await Promise.all([memberAPI<Grant[]>('/api/matrimony/delegates'),memberAPI<Pick[]>('/api/matrimony/shortlist'),memberAPI<Family[]>('/api/families')]);setGrants(g);setPicks(p);setFamilies(f.filter(x=>x.mine||x.accepted));if(owner&&!g.some(x=>x.owner===owner&&x.available)){setOwner('');setCandidates([]);}}
 useEffect(()=>{void action.run(refresh);},[]);
 function act(body:unknown){void action.run(async()=>{await memberAPI('/api/matrimony/delegates','POST',body);setCandidates([]);await refresh();});}
 return <><section className="card"><p className="kicker">Support, with boundaries</p><h2>Family assistance</h2><p>Invite an adult member of your private family group to suggest a shortlist. Your matrimony profile must be active. Grants expire after 30 days and require their acceptance. Helpers cannot access messages, contact details, publish your profile or send interests on your behalf.</p>
 <form onSubmit={e=>{e.preventDefault();act({action:'grant',handle,family_id:family});}}><Field label="Helper's account handle"><input required value={handle} onChange={e=>setHandle(e.target.value)}/></Field><Field label="Shared family group"><select required value={family} onChange={e=>setFamily(e.target.value)}><option value="">Choose</option>{families.map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select></Field><button disabled={action.busy}>Grant shortlist permission</button></form>
 <button disabled={action.busy} onClick={()=>void action.run(refresh)}>Refresh family assistance</button><Feedback {...action}/>
 {grants.map(g=><article className="card" key={g.owner+g.delegate}><h3>{g.mine?'Your helper':'Helping'}: @{g.handle}</h3><p>{g.accepted?'Accepted':'Awaiting acceptance'} · expires {new Date(g.expires_at).toLocaleDateString()}</p>{g.mine?<button onClick={()=>act({action:'revoke',delegate:g.delegate})}>Revoke helper</button>:<>{!g.accepted&&<button onClick={()=>act({action:'accept',owner:g.owner})}>Accept helper invitation</button>}<button onClick={()=>act({action:'leave',owner:g.owner})}>Decline / stop helping</button>{g.available&&<button disabled={action.busy} onClick={()=>void action.run(async()=>{setCandidates([]);setOwner(g.owner);setCandidates((await memberAPI<{items:Candidate[]}>(`/api/matrimony/assistance/${g.owner}`)).items);})}>Find suggestions</button>}</>}</article>)}</section>
 <div className="grid-3">{candidates.map(c=><article className="card" key={c.id}><h3>@{c.handle} · {c.age}</h3><p>{c.details.introduction}</p><p>{c.details.city}</p><p>Shared interests: {c.shared_interests.join(', ')||'None listed'}</p>{c.reasons&&c.reasons.length>0&&<p className="small">Why suggested: {c.reasons.join(' · ')}</p>}<button disabled={action.busy} onClick={async()=>{const note=await fb.prompt({title:'Suggest this profile',label:'Why might this be worth exploring? (optional)',max:500});if(note!==null)void action.run(async()=>{await memberAPI('/api/matrimony/shortlist','POST',{owner,candidate:c.id,note});await refresh();action.setMessage('Suggestion saved. The profile owner decides whether to make contact.');});}}>Suggest this profile</button></article>)}</div>
 <section className="card"><h3>Family shortlist</h3>{!picks.length&&<p>No current suggestions.</p>}{picks.map(p=><article key={p.owner+p.delegate+p.candidate}><p><strong>@{p.candidate_handle}</strong> · suggested by @{p.delegate_handle}</p><p>{p.note}</p><button disabled={action.busy} onClick={()=>void action.run(async()=>{await memberAPI('/api/matrimony/shortlist','POST',{owner:p.owner,delegate:p.delegate,candidate:p.candidate,remove:true});await refresh();})}>Remove suggestion</button></article>)}<p>The owner reviews suggestions and initiates any contact from Matrimony. Revoked grants and blocked or hidden profiles are not shown.</p></section></>;
}
