import { useEffect, useState } from 'react';
import { Avatar, Feedback, Field, memberAPI, useAction } from './shared';
type Details = { introduction: string; city: string; occupation: string; education: string; languages: string; timeline: string; children: string; relocation: string; lifestyle: string; values: string; min_age: number; max_age: number };
const blank: Details = { introduction: '', city: '', occupation: '', education: '', languages: '', timeline: '', children: '', relocation: '', lifestyle: '', values: '', min_age: 18, max_age: 70 };
type Candidate = { id: string; handle: string; details: Details; avatar: string; accent: string; age: number; shared_interests: string[]; same_city: boolean; same_timeline: boolean; discuss_relocation: boolean };
type Interest = { id: string; handle: string; outgoing: boolean; status: string };
type Message = { id: number; body: string; mine: boolean; created_at: string };
function Conversation({ peer }: { peer: Interest }) {
 const action = useAction(), [messages, setMessages] = useState<Message[]>([]), [body, setBody] = useState('');
 const load = async () => setMessages(await memberAPI(`/api/matrimony/messages/${peer.id}`));
 useEffect(() => { setMessages([]); void action.run(load); }, [peer.id]);
 return <section className="card"><h3>Conversation with @{peer.handle}</h3><p>Your number stays private. Share contact details only when you are ready.</p><button onClick={() => void action.run(load)}>Refresh messages</button><div className="member-messages">{messages.map(m => <p key={m.id} className={m.mine ? 'mine' : ''}><strong>{m.mine ? 'You' : peer.handle}</strong><br />{m.body}</p>)}</div><form onSubmit={e => { e.preventDefault(); void action.run(async () => { await memberAPI(`/api/matrimony/messages/${peer.id}`, 'POST', { body }); setBody(''); await load(); }); }}><Field label="Message"><textarea required maxLength={2000} value={body} onChange={e => setBody(e.target.value)} /></Field><button disabled={action.busy}>Send message</button></form><Feedback {...action} /></section>;
}
export function Matrimony() {
 const action = useAction(), [details, setDetails] = useState<Details>(blank), [active, setActive] = useState(false), [consent, setConsent] = useState(false);
 const [candidates, setCandidates] = useState<Candidate[]>([]), [interests, setInterests] = useState<Interest[]>([]), [peer, setPeer] = useState<Interest | null>(null);
 const refresh = async () => { setInterests(await memberAPI('/api/matrimony/interests')); };
 useEffect(() => { void action.run(async () => { const rows = await memberAPI<{ active: boolean; details: Details }[]>('/api/matrimony/me'); if (rows[0]) { setActive(rows[0].active); setDetails({ ...blank, ...rows[0].details }); } await refresh(); }); }, []);
 const interest = (target: string, value: string) => void action.run(async () => { await memberAPI('/api/matrimony/interests', 'POST', { target, action: value }); if (value === 'unmatch') setPeer(null); await refresh(); });
 return <><section className="card"><p className="kicker">A life you choose together</p><h2>Matrimony</h2><p>Join intentionally. Your published introduction is separate from your private profile, and conversations open only after interest is accepted.</p><p className="small muted">Age is self-declared. Account and phone access do not establish identity or guarantee safety.</p>
 <details><summary>{active ? 'Edit or pause my matrimony profile' : 'Create my matrimony profile'}</summary><form onSubmit={e => { e.preventDefault(); void action.run(async () => { await memberAPI('/api/matrimony/me', 'PUT', { active, consent, details }); action.setMessage(active ? 'Matrimony profile published.' : 'Profile saved privately; discovery paused.'); }); }}>
 <div className="grid-2">{(['introduction', 'city', 'occupation', 'education', 'languages', 'timeline', 'children', 'relocation', 'lifestyle', 'values'] as const).map(key => <Field key={key} label={key}><textarea maxLength={key === 'introduction' ? 1000 : key === 'values' ? 500 : 100} value={details[key]} onChange={e => setDetails({ ...details, [key]: e.target.value })} placeholder={key === 'timeline' ? 'For example, within two years' : ''} /></Field>)}
 <Field label="Preferred minimum age"><input type="number" min={18} max={100} value={details.min_age} onChange={e => setDetails({ ...details, min_age: +e.target.value })} /></Field><Field label="Preferred maximum age"><input type="number" min={18} max={100} value={details.max_age} onChange={e => setDetails({ ...details, max_age: +e.target.value })} /></Field></div>
 <label><input type="checkbox" checked={active} onChange={e => setActive(e.target.checked)} /> Make this profile discoverable</label>{active && <label><input type="checkbox" required checked={consent} onChange={e => setConsent(e.target.checked)} /> I am an eligible adult and consent to sharing these details with participating members.</label>}<button disabled={action.busy}>Save matrimony profile</button></form></details><button disabled={action.busy} onClick={() => void action.run(async () => { setCandidates(await memberAPI('/api/matrimony/discover')); })}>Discover compatible profiles</button><Feedback {...action} /></section>
 <div className="grid-3">{candidates.map(p => <article className="card" key={p.id}><Avatar kind={p.avatar} accent={p.accent} /><h3>@{p.handle} · {p.age}</h3><p>{p.details.introduction}</p><p>{p.details.city} · {p.details.occupation}</p><p>Values: {p.details.values || 'Not shared'}</p><p>Shared interests: {p.shared_interests.join(', ') || 'None listed yet'}</p>{p.same_city && <span className="tag">Same city</span>}{p.same_timeline && <span className="tag">Similar timeline</span>}{p.discuss_relocation && <p>Discuss: your relocation preferences differ.</p>}<button disabled={action.busy} onClick={() => interest(p.id, 'send')}>Express interest</button></article>)}</div>
 <section className="card"><h3>Interests & connections</h3>{!interests.length && <p>No interests yet.</p>}{interests.map((i, index) => <div className="community-row" key={i.id + index}><span>@{i.handle} · {i.outgoing ? 'Sent' : 'Received'} · {i.status}</span>{i.status === 'pending' && !i.outgoing && <><button onClick={() => interest(i.id, 'accept')}>Accept</button><button onClick={() => interest(i.id, 'decline')}>Decline</button></>}{i.status === 'accepted' && <><button onClick={() => setPeer(i)}>Open conversation</button><button onClick={() => interest(i.id, 'unmatch')}>Unmatch</button></>}<button onClick={() => void action.run(async () => { await memberAPI('/api/community/blocks', 'POST', { target: i.id, block: true }); setPeer(null); await refresh(); })}>Block</button></div>)}</section>{peer && <Conversation key={peer.id} peer={peer} />}
 <p className="disclaimer">Suggestions reflect stated preferences, not a prediction of relationship success. Optional Kundali comparison remains available under Matching.</p>
 </>;
}
