import { useEffect, useState } from 'react';
import { Avatar, Feedback, Field, memberAPI, useAction } from './shared';
type Settings = { community: boolean; birth_date: string; avatar: string; accent: string; public_bio: string; interests: string[]; links: string[]; preferences: Record<string, string> };
const initial: Settings = { community: false, birth_date: '', avatar: 'sun', accent: '#d6b467', public_bio: '', interests: [], links: [], preferences: {} };
export function CommunitySettings() {
 const action = useAction(), [settings, setSettings] = useState<Settings>(initial), [interests, setInterests] = useState(''), [links, setLinks] = useState('');
 const [blocks, setBlocks] = useState<{ id: string; handle: string }[]>([]);
 useEffect(() => { void action.run(async () => { const rows = await memberAPI<Settings[]>('/api/community/settings'); if (rows[0]) { setSettings({ ...initial, ...rows[0] }); setInterests(rows[0].interests.join(', ')); setLinks(rows[0].links.join('\n')); } setBlocks(await memberAPI('/api/community/blocks')); }); }, []);
 const questions = { weekend: 'Your ideal weekend', communication: 'How you prefer to communicate', learning: 'Something you want to learn', family: 'What family involvement means to you', values: 'Values you want to live by' };
 return <><form className="card" onSubmit={e => { e.preventDefault(); void action.run(async () => { await memberAPI('/api/community/settings', 'PUT', { ...settings, interests: [...new Set(interests.split(',').map(x => x.trim()).filter(Boolean))], links: links.split('\n').map(x => x.trim()).filter(Boolean) }); action.setMessage('Profile and privacy choices saved.'); }); }}>
 <p className="kicker">Make it yours</p><h2>Profile & interests</h2><p>Your public bio, avatar, interests and chosen social links become visible only when you enable community. Birth date and reflection answers stay private.</p>
 <div className="community-row"><Avatar kind={settings.avatar} accent={settings.accent} /><Field label="Your character"><select value={settings.avatar} onChange={e => setSettings({ ...settings, avatar: e.target.value })}>{['sun', 'moon', 'star', 'leaf', 'mountain'].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="Accent colour"><input type="color" value={settings.accent} onChange={e => setSettings({ ...settings, accent: e.target.value })} /></Field></div>
 <Field label="Private birth date"><input required type="date" value={settings.birth_date || ''} onChange={e => setSettings({ ...settings, birth_date: e.target.value })} /></Field>
 <Field label="Community introduction"><textarea maxLength={1000} rows={4} value={settings.public_bio} onChange={e => setSettings({ ...settings, public_bio: e.target.value })} /></Field>
 <Field label="Interests, separated by commas"><input maxLength={800} value={interests} onChange={e => setInterests(e.target.value)} placeholder="Hiking, books, cooking, classical music" /></Field>
 <Field label="Your social profile links (one HTTPS link per line)"><textarea rows={3} value={links} onChange={e => setLinks(e.target.value)} /></Field><p className="small muted">Links are self-declared, not identity verification. We do not search for hidden accounts or import social posts.</p>
 <h3>My reflections</h3><p>Describe yourself in your own words. These prompts are private reflections, not a psychological test or character score.</p>
 {Object.entries(questions).map(([key, label]) => <Field key={key} label={label}><textarea maxLength={200} value={settings.preferences[key] || ''} onChange={e => setSettings({ ...settings, preferences: { ...settings.preferences, [key]: e.target.value } })} /></Field>)}
 <label><input type="checkbox" checked={settings.community} onChange={e => setSettings({ ...settings, community: e.target.checked })} /> Join the adult community and share my community introduction, avatar, interests and links.</label>
 <button disabled={action.busy} className="primary">Save profile & privacy</button><Feedback {...action} />
 </form><section className="card"><h3>Blocked accounts</h3>{!blocks.length && <p>No blocked accounts.</p>}{blocks.map(b => <p key={b.id}>@{b.handle} <button onClick={() => void action.run(async () => { await memberAPI('/api/community/blocks', 'POST', { target: b.id, block: false }); setBlocks(await memberAPI('/api/community/blocks')); })}>Unblock</button></p>)}<p>Unblocking does not restore previous follows or matches.</p></section></>;
}

export function Security() {
 const action = useAction(), [status, setStatus] = useState<any>(null), [password, setPassword] = useState(''), [recovery, setRecovery] = useState('');
 const [phone, setPhone] = useState(''), [code, setCode] = useState(''), [consent, setConsent] = useState(false);
 const load = async () => setStatus(await memberAPI('/api/me/security'));
 useEffect(() => { void action.run(load); }, []);
 return <section className="card"><h2>Account security</h2><p>{status?.sessions || 0} active session(s). Phone: {status?.phone_verified ? 'Verified access to number' : 'Not verified'}.</p>
 <Field label="Current password"><input type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} /></Field>
 <h3>Recovery key</h3><p>Generate a private recovery key and keep it somewhere safe. It is shown once and replaces any previous recovery key.</p><button disabled={action.busy || !password} onClick={() => void action.run(async () => { const result = await memberAPI('/api/me/recovery-key', 'POST', { password }); setRecovery(result.recovery_key); setPassword(''); await load(); })}>Generate recovery key</button>{recovery && <div className="recovery-key"><code>{recovery}</code><p>Store this securely. Anyone with this key and your handle can reset your password.</p></div>}
 <h3>Mobile number</h3>{!status?.phone_available ? <p>SMS verification is unavailable until the delivery provider is configured. Your profile will not display a verified-phone badge.</p> : <><form onSubmit={e => { e.preventDefault(); void action.run(async () => { await memberAPI('/api/me/phone/start', 'POST', { phone, password, consent }); action.setMessage('Code sent. Enter it below within 10 minutes.'); }); }}><Field label="Phone in international format"><input type="tel" placeholder="+919876543210" required value={phone} onChange={e => setPhone(e.target.value)} /></Field><label><input type="checkbox" required checked={consent} onChange={e => setConsent(e.target.checked)} /> Send a verification SMS to my number.</label><button disabled={action.busy}>Send code</button></form><form onSubmit={e => { e.preventDefault(); void action.run(async () => { await memberAPI('/api/me/phone/check', 'POST', { code }); setCode(''); await load(); }); }}><Field label="Verification code"><input inputMode="numeric" autoComplete="one-time-code" value={code} onChange={e => setCode(e.target.value)} /></Field><button disabled={action.busy}>Verify number</button></form></>}
 <h3>Sessions & data</h3><button disabled={action.busy} onClick={() => void action.run(async () => { const data = await memberAPI('/api/me/export'); const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = 'antariksha-account-data.json'; a.click(); URL.revokeObjectURL(url); })}>Export account data</button><button onClick={() => void action.run(async () => { await memberAPI('/api/me/logout-all', 'POST', {}); location.hash = 'account'; location.reload(); })}>Sign out on all devices</button><Feedback {...action} /></section>;
}

export function Moderation() {
 const action = useAction(), [reports, setReports] = useState<{ id: number; post_id: number; reason: string; caption: string }[]>([]);
 const load = async () => setReports(await memberAPI('/api/community/moderation'));
 useEffect(() => { void action.run(load); }, []);
 return <section className="card"><h2>Moderation queue</h2><p>Access is restricted to configured moderators. Actions are recorded.</p>{reports.map(report => <article className="card" key={report.id}><h3>Post {report.post_id}</h3><p>{report.caption}</p><p>Report: {report.reason}</p><button onClick={() => void action.run(async () => { await memberAPI('/api/community/moderation', 'POST', { report: report.id, hide: true }); await load(); })}>Hide post</button><button onClick={() => void action.run(async () => { await memberAPI('/api/community/moderation', 'POST', { report: report.id, hide: false }); await load(); })}>Dismiss report</button></article>)}<Feedback {...action} /></section>;
}
