import {useState} from 'react';
import {BirthFields,draftFrom,resolveDraft} from './kundali/BirthForm';
import {accountBirth} from './common/profiles';
import {memberAPI} from './community/shared';
import './readings.css';

type NumberMeaning={number:number;steps:number[];meaning:string;reflection:string};
type Numbers={method:string;name_used:string;note:string;life_path:NumberMeaning;birthday:NumberMeaning;personal_year:NumberMeaning;expression?:NumberMeaning;soul_urge?:NumberMeaning;personality?:NumberMeaning};
type Tarot={cards:{id:string;name:string;meaning:string;reflection:string;reversed:boolean;position:string}[];deck:string;method:string;note:string};
type Western={summary:string[];note:string;houses:{system:string;cusps:number[]};planets:{id:string;name:string;longitude:number;sign:string;degree:number;house:number;retrograde:boolean;meaning:string}[];aspects:{first:string;second:string;name:string;orb:number;meaning:string}[]};

export function MoreReadings(){
 const [mode,setMode]=useState<'numerology'|'western'|'tarot'>('numerology');
 return <div className="page more-readings"><header className="page-heading"><p className="kicker">Three ways to reflect</p><h1>More readings</h1><p>Clear explanations, with the method behind each result. These symbolic traditions are not scientific personality tests or predictions.</p></header><div className="tabs" role="tablist" aria-label="Reading method">{(['numerology','western','tarot'] as const).map(v=><button key={v} role="tab" aria-selected={mode===v} onClick={()=>setMode(v)}>{v==='western'?'Western astrology':v[0].toUpperCase()+v.slice(1)}</button>)}</div><section role="tabpanel" aria-label={mode} key={mode}>{mode==='numerology'?<Numerology/>:mode==='western'?<WesternChart/>:<TarotDraw/>}</section><p className="disclaimer">For reflection, not certainty. Use qualified professionals for medical, legal or financial decisions. These readings are not added to your public profile, and switching methods clears the current result.</p></div>;
}
function Numerology(){
 const [date,setDate]=useState(accountBirth()?.date??''),[name,setName]=useState(''),[year,setYear]=useState(new Date().getFullYear()),[result,setResult]=useState<Numbers>(),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const entries:[keyof Numbers,string,string][]=[['life_path','Life path','A broad reflection based on your birth date.'],['birthday','Birthday','A theme drawn from the day of the month.'],['personal_year','Personal year','A reflection prompt for the year you chose.'],['expression','Expression','A name-based prompt about how you express yourself.'],['soul_urge','Inner motivations','A prompt based on vowels, traditionally called soul urge.'],['personality','Outward style','A prompt based on consonants—not a measurement of your personality.']];
 return <><form className="card" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setResult(undefined);try{setResult(await memberAPI<Numbers>('/api/numerology','POST',{date,name,year}));}catch(e){setError(String(e));}finally{setBusy(false);}}}><h2>Numerology</h2><p>Start with your birthday. Add a Latin-letter name if you want the optional name-based numbers.</p><div className="grid-2"><label className="field">Birth date<input type="date" required min="1800-01-01" max="2399-12-31" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field">Name for numerology (optional)<input maxLength={100} value={name} onChange={e=>setName(e.target.value)} autoComplete="off"/></label><label className="field">Reading year<input type="number" required min={1800} max={2399} value={year} onChange={e=>setYear(+e.target.value)}/></label></div><button className="primary" disabled={busy}>{busy?'Calculating…':'Read my numbers'}</button>{error&&<p role="alert">{error}</p>}</form>{result&&<div aria-live="polite"><div className="grid-2">{entries.map(([key,label,description])=>{const value=result[key];if(!value||typeof value==='string')return null;return <article className="card" key={key}><p className="kicker">{label}</p><div className="reading-number">{value.number}</div><p className="small muted">{description}</p><p>{value.meaning}</p><p className="reflection-question">{value.reflection}</p><details><summary>How it was calculated</summary><p>Reduction: {value.steps.join(' → ')}{['expression','soul_urge','personality'].includes(key)?` · Letters used: ${result.name_used}`:''}</p></details></article>;})}</div><details className="card"><summary>Our numerology convention</summary><p>{result.method}</p><p>{result.note}</p></details></div>}</>;
}
function TarotDraw(){
 const [count,setCount]=useState(3),[reversals,setReversals]=useState(false),[result,setResult]=useState<Tarot>(),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <><section className="card"><h2>Tarot · a moment to reflect</h2><p>Hold a question in mind. You do not need to type or send it. A random draw offers prompts—not evidence about other people or a fixed future.</p><div className="grid-2"><label className="field">Spread<select value={count} onChange={e=>setCount(+e.target.value)}><option value={1}>One card · focus</option><option value={3}>Three cards · focus, challenge, next step</option></select></label><label className="consent"><input type="checkbox" checked={reversals} onChange={e=>setReversals(e.target.checked)}/>Include reversed cards</label></div><button className="primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');setResult(undefined);try{setResult(await memberAPI<Tarot>('/api/tarot','POST',{count,reversals}));}catch(e){setError(String(e));}finally{setBusy(false);}}}>{busy?'Drawing…':'Draw cards'}</button>{error&&<p role="alert">{error}</p>}</section>{result&&<div aria-live="polite"><div className="tarot-spread">{result.cards.map(c=><article className="card tarot-card" key={c.id}><p className="kicker">{c.position}</p><div className="tarot-emblem" aria-hidden="true"><span>✧</span></div><h3>{c.name}</h3><p className="small muted">{c.reversed?'Reversed · an inward reflection':'Upright'}</p><p>{c.meaning}</p><p className="reflection-question">{c.reflection}</p>{c.reversed&&<p className="small">Consider what feels blocked, excessive or worth approaching differently. Reversed does not mean bad luck.</p>}</article>)}</div><details className="card"><summary>About this draw</summary><p>{result.method}</p><p>{result.deck}</p><p>{result.note}</p></details></div>}</>;
}
function WesternChart(){
 const [draft,setDraft]=useState(draftFrom),[system,setSystem]=useState('placidus'),[result,setResult]=useState<Western>(),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <><form className="card" onSubmit={async e=>{e.preventDefault();setResult(undefined);const details=resolveDraft(draft);if(typeof details==='string'){setError(details);return;}setBusy(true);setError('');const{date,time,lat,lon,tz}=details;try{setResult(await memberAPI<Western>('/api/western','POST',{date,time,lat,lon,tz,system}));}catch(e){setError(String(e));}finally{setBusy(false);}}}><h2>Western astrology</h2><p>This uses the tropical zodiac, so signs can differ from your Vedic kundali. Exact birth time and place are needed for the rising sign and houses.</p><BirthFields draft={draft} onChange={setDraft} showName={false}/><label className="field">House system<select value={system} onChange={e=>setSystem(e.target.value)}><option value="placidus">Placidus</option><option value="whole_sign">Whole sign</option></select></label><button className="primary" disabled={busy}>{busy?'Calculating…':'Read my Western chart'}</button>{error&&<p role="alert">{error}</p>}</form>{result&&<div aria-live="polite"><article className="card"><h2>Your Sun, Moon and rising sign</h2>{result.summary.map((s,i)=><p key={i}>{s}</p>)}</article><div className="grid-2">{result.planets.map(p=><article className="card" key={p.id}><h3>{p.name} · {p.sign}</h3><p>{p.meaning}</p><details><summary>Position details</summary><p>{p.degree.toFixed(2)}° within {p.sign} · house {p.house}{p.retrograde?' · retrograde (apparent backward motion)':''}</p><p>Tropical longitude {p.longitude.toFixed(4)}°</p></details></article>)}</div><article className="card"><h3>How the themes connect</h3><p>These angles between planets are called aspects. They are symbolic prompts, not promises or conflicts you must experience.</p>{result.aspects.map(a=><p key={a.first+a.second}><b>{a.first} & {a.second}</b>: {a.meaning} <span className="muted small">({a.name}, {a.orb.toFixed(2)}° from exact)</span></p>)}<details><summary>Calculation method</summary><p>{result.note}</p><p>{result.houses.system} house boundaries: {result.houses.cusps.map(x=>`${x.toFixed(2)}°`).join(', ')}</p></details></article></div>}</>;
}
